---
- name: "set cassandra as owner/group rwx/rwx/rx {{ cassandra22x_data_path }}/{{ keyspace_name }}"
  file: 
    dest: "{{ cassandra22x_data_path }}/{{ keyspace_name }}/{{ item }}/"
    owner: "{{ cassandra22x_linux_user }}"
    group: "{{ cassandra22x_linux_group }}"
    mode: "{{ cassandra22x_cassandra_default_recursive_mode }}"
    recurse: yes
  with_items: 
        - "{{ column_families_disk }}"