--- 
- name: "include the {{ cassandra22x_restore_vars }}/{{ cassandra22x_src_environment }}/{{ cassandra22x_src_cluster_node }}/{{ snapshot_keyspace_yml }} vars"
  include_vars:
    file: "{{ cassandra22x_restore_vars }}/{{ cassandra22x_src_environment }}/{{ cassandra22x_src_cluster_node }}/{{ snapshot_keyspace_yml }}"
    
- debug:
    msg: "keyspace_name = {{ keyspace_name }} & snapshot_name = {{ snapshot_name }}"    

- import_tasks: configure_local_archive_path_for_keyspace.yml
- import_tasks: local_unarchive_snapshot_logs.yml