---
- name: "create {{ cassandra22x_remote_archive_path }}"
  file:
    path: "{{ cassandra22x_remote_archive_path }}"
    state: directory
    owner: root
    group: root
    mode: "{{ cassandra22x_root_default_directory_mode }}"

- name: "create {{ cassandra22x_remote_archive_path_archived_logs }}"
  file:
    path: "{{ cassandra22x_remote_archive_path_archived_logs }}"
    state: directory
    owner: root
    group: root    
    mode: "{{ cassandra22x_root_default_directory_mode }}"
    
- name: "create {{ cassandra22x_remote_archive_path_archived_ansible_restore_vars }}"
  file:
    path: "{{ cassandra22x_remote_archive_path_archived_ansible_restore_vars }}"
    state: directory
    owner: root
    group: root    
    mode: "{{ cassandra22x_root_default_directory_mode }}"
  delegate_to: 127.0.0.1    